config/routes.rb
Rails.application.routes.draw do
  resources :scans

  root 'scans#index'

end

app/models/scan.rb
class Scan < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  require 'rest_client'

  def index
    @scans = Scan.all
  end
  
  def show
    @scan = Scan.where(id: params[:id]).first
  end

  def new
    @scan = Scan.new
  end

  def create
    @scan = Scan.new

    @scan.filename = params[:scan][:file].original_filename
    
    # Save file to disk
    directory = "public/uploads"
    FileUtils.mkdir_p directory
    path = File.join(directory, @scan.filename)
    File.open(path, "wb") { |f| f.write(params[:scan][:file].read) }

    # Call to tika server
    begin
      tika_out = ""
      
      #### Can't make it work, always getting "405 Method Not Allowed" 
      # file = File.open(path, "r")
      # RestClient.post('http://0.0.0.0:9998/meta', upload: file)

      #### Other way
      # JSON output
      #tika_out = `curl -H \"Accept: application/json\" -T #{path} http://0.0.0.0:9998/meta`

      # Plaintext output
      tika_out = `curl -T #{path} http://0.0.0.0:9998/meta`

      @scan.body = tika_out
    rescue
      @scan.body = "Error"
    end

    @scan.save
    redirect_to scan_path(@scan)
  end

  def destroy
    @scan = Scan.where(id: params[:id]).first
    @scan.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tikaweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Tika Web</h1>

<%= yield %>

</body>
</html>

app/views/scans/index.html.erb
<div>
	<p><%= link_to "New scan", new_scan_path %></p>
</div>

<h2>Scans</h2>
<div>
	<% @scans.each do |scan| %>
		<p><%= link_to scan.filename, scan_path(scan) %> - <%= link_to "delete", scan_path(scan), method: :delete %></p>
	<% end %>
</div>

app/views/scans/new.html.erb
<div>
	<p><%= link_to "Scans Index", root_path %></p>
</div>

<h2>New scan</h2>
<div>
	<%= form_tag scans_path, { :multipart => true } do %>
    	<p>
    		<%= file_field_tag 'scan[file]' %>
    	</p>
    	<p>
    		<%= submit_tag "Upload" %>
    	</p>
	<% end %>
</div>

app/views/scans/show.html.erb
<div>
	<p><%= link_to "Scans Index", root_path %></p>
</div>

<h2><%= @scan.filename %></h2>
<div>
	<pre>
		<%= @scan.body %>
	</pre>
</div>